camunda:
  bpm:
    history-level: FULL
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    filter:
      create: All tasks
    eventing:
      execution: true
      history: true
      task: true
spring:
  main:
    allow-bean-definition-overriding: true