spring:
   main:
      allow-bean-definition-overriding: true
   datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/processflow
      username: postgres
      password: root
      driverClassName: org.postgresql.Driver
      initialization-mode: always
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate:
         ddl-auto: create
      properties:
         hibernate.temp.use_jdbc_metadata_defaults: false  
      show-sql: false
camunda:
   bpm:
      admin-user:
         id: admin
         password: admin